apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-scapy-deployment
  namespace: ipspoof
  labels:
    app: flask-scapy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-scapy
  template:
    metadata:
      labels:
        app: flask-scapy
    spec:
      containers:
      - name: flask
        image: absarhussain/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        # securityContext:
        #   capabilities:
        #     add:
        #       - all
        #       - NET_RAW
        #   allowPrivilegeEscalation: false
        #   runAsUser: 0
      - name: python
        image: absarhussain/scapy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: ipspoof
spec:
  type: ClusterIP
  selector:
    app: flask-scapy
  ports:
  - port: 80
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-udp
  namespace: ipspoof
spec:
  type: ClusterIP
  selector:
    app: flask-scapy
  ports:
  - protocol: UDP
    port: 80
    targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: scapy-service
  namespace: ipspoof
spec:
  type: ClusterIP
  selector:
    app: flask-scapy
  ports:
  - port: 80
    targetPort: 80