apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: ipspoof
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: absarhussain/ubuntu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # securityContext:
        #   capabilities:
        #     add:
        #       - all
        #       - NET_RAW
        #   allowPrivilegeEscalation: false
        #   runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: ipspoof
spec:
  type: ClusterIP
  selector:
    app: ubuntu
  ports:
  - port: 80
    targetPort: 80
